-- Tiered schedules (spec 9). One row per (site, tier): the tier IS the identity, which is what
-- lets the UI edit "the pulse schedule" and stops two pulse crons racing into one 03:00 window.
-- Rows are disabled, never deleted (D38) — the dispatcher seeds missing ones on every tick, so a
-- deleted row would come back.
CREATE TABLE schedule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT NOT NULL REFERENCES site (id) ON DELETE CASCADE,
    scope TEXT NOT NULL,
    cron TEXT NOT NULL,
    -- Per schedule, not global: "03:00 local" is two different UTC instants either side of a
    -- daylight-saving change, and a stored UTC hour drifts an hour twice a year.
    timezone TEXT NOT NULL DEFAULT 'Europe/Berlin',
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    last_fired_at TIMESTAMPTZ,
    -- Stored rather than derived (D39): the tick is then one index scan instead of parsing every
    -- site's three cron expressions to find out that none of them is due.
    next_fire_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX ux_schedule_site_scope ON schedule (site_id, scope);
CREATE INDEX ix_schedule_due ON schedule (next_fire_at) WHERE enabled;
