-- Pattern mutes alongside per-finding mutes (spec 6.3). Two patterns, not one (D48): spec 6.2
-- made "what is broken" and "where it was found" different columns, and a single "URL pattern"
-- would have to guess which one the colleague meant.
CREATE TABLE mute_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT REFERENCES site (id) ON DELETE CASCADE,   -- NULL = every site (ADMIN only)
    check_type TEXT,                                          -- NULL = every check
    subject_pattern TEXT,                                     -- glob over finding.subject_key
    location_pattern TEXT,                                    -- glob over finding.location_key
    reason TEXT NOT NULL,
    created_by TEXT,
    -- Mandatory, like a per-finding mute and for the same reason (spec 6.3).
    expires_at TIMESTAMPTZ NOT NULL,
    expired_at TIMESTAMPTZ,                                   -- stamped by the sweep, never cleared
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 0,
    -- D48. A rule with all three empty mutes the whole site, and that is one empty form submit
    -- away. Enforced here as well as in Java because the Java guard is the one a later caller
    -- forgets to go through.
    CONSTRAINT ck_mute_rule_has_criterion CHECK (
        check_type IS NOT NULL OR subject_pattern IS NOT NULL OR location_pattern IS NOT NULL)
);

CREATE INDEX ix_mute_rule_active ON mute_rule (site_id) WHERE expired_at IS NULL;

-- Which rule muted a finding: needed to un-mute exactly those rows when the rule is deleted or
-- expires, and to show "stummgeschaltet durch Regel" on the finding. NULL for a manual mute.
ALTER TABLE finding ADD COLUMN muted_by_rule_id BIGINT REFERENCES mute_rule (id) ON DELETE SET NULL;
CREATE INDEX ix_finding_muted_by_rule ON finding (muted_by_rule_id) WHERE muted_by_rule_id IS NOT NULL;
