CREATE TABLE notification_recipient (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT NOT NULL REFERENCES site (id) ON DELETE CASCADE,
    email TEXT NOT NULL CHECK (email <> ''),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX ux_notification_recipient_site_email
    ON notification_recipient (site_id, lower(email));
