-- Per-site credential store (spec 6.1, 10.4). The secret is AES-GCM ciphertext from SecretBox;
-- every row in that column is encrypted, so no `encrypted` flag is needed. The username is
-- deliberately in clear: the screen must show which account is configured (D97).
CREATE TABLE credential (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT NOT NULL REFERENCES site (id) ON DELETE CASCADE,
    name TEXT NOT NULL CHECK (name <> ''),
    username TEXT,
    secret TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX ux_credential_site_name ON credential (site_id, lower(name));
