-- Journeys belong to a site: a journey resolves {{cred.…}} against one site's store (spec 10.4),
-- and there is no cross-site credential. Steps are jsonb rather than a child table because they
-- are only ever read and written as a whole ordered list, never queried into.
CREATE TABLE journey (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT NOT NULL REFERENCES site (id) ON DELETE CASCADE,
    name TEXT NOT NULL CHECK (name <> ''),
    enabled BOOLEAN NOT NULL DEFAULT true,
    steps JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX ux_journey_site_name ON journey (site_id, lower(name));
