-- Site catalog entry: base URL, crawl budget, include/exclude patterns, robots policy,
-- form-test mode and User-Agent override (spec 6.1).
CREATE TABLE site (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    base_url TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    max_pages INTEGER NOT NULL DEFAULT 300,
    max_depth INTEGER NOT NULL DEFAULT 5,
    max_duration_seconds INTEGER NOT NULL DEFAULT 1800,
    include_patterns JSONB NOT NULL DEFAULT '[]'::jsonb,
    exclude_patterns JSONB NOT NULL DEFAULT '[]'::jsonb,
    pinned_key_pages JSONB NOT NULL DEFAULT '[]'::jsonb,
    respect_robots BOOLEAN NOT NULL DEFAULT TRUE,
    user_agent TEXT,
    form_test_mode TEXT NOT NULL DEFAULT 'NO_SUBMIT',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX ux_site_base_url ON site (base_url);
