-- Per-check enable/config/severity override for a site (spec 7.1).
CREATE TABLE site_check_setting (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT NOT NULL REFERENCES site (id) ON DELETE CASCADE,
    check_type TEXT NOT NULL,
    enabled BOOLEAN NOT NULL,
    severity_override TEXT,
    config JSONB NOT NULL DEFAULT '{}'::jsonb,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ux_site_check UNIQUE (site_id, check_type)
);
