-- A WebTest run: one row per crawl, leased by a worker for durable job execution (spec 14).
CREATE TABLE run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT NOT NULL REFERENCES site (id) ON DELETE CASCADE,
    trigger_type TEXT NOT NULL,
    scope TEXT NOT NULL,
    status TEXT NOT NULL,

    queued_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,

    lease_owner TEXT,
    lease_expires_at TIMESTAMPTZ,

    pages_visited INTEGER NOT NULL DEFAULT 0,
    pages_failed INTEGER NOT NULL DEFAULT 0,
    findings_total INTEGER NOT NULL DEFAULT 0,

    -- Coverage is load-bearing: resolution applies only within it (spec 6.4).
    covered_check_types JSONB NOT NULL DEFAULT '[]'::jsonb,
    covered_urls JSONB NOT NULL DEFAULT '[]'::jsonb,
    partial_coverage BOOLEAN NOT NULL DEFAULT FALSE,
    budget_stop_reason TEXT,

    -- Soft-404 probe taken at crawl start (spec 7.1). SimHash of the probe page's text.
    soft404_simhash BIGINT,
    soft404_status INTEGER,
    soft404_text_length INTEGER,

    baseline_accepted_at TIMESTAMPTZ,
    error_message TEXT,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX ix_run_queue ON run (status, queued_at);
CREATE INDEX ix_run_site_recent ON run (site_id, queued_at DESC);

-- The backstop for "one run at a time per site" (spec 5.3). Under READ COMMITTED the
-- NOT EXISTS guard in the claim statement cannot see another transaction's uncommitted
-- RUNNING row; this index can.
CREATE UNIQUE INDEX ux_run_single_active_per_site ON run (site_id) WHERE status = 'RUNNING';
