-- The crawl frontier (spec 14). A table rather than an in-memory queue: live progress,
-- resumability after a restart, and orphaned-run recovery. Claimed and completed in
-- batches (spec 6.5) so a 15,000-page run costs hundreds of statements, not tens of thousands.
CREATE TABLE crawl_queue_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL REFERENCES run (id) ON DELETE CASCADE,
    url TEXT NOT NULL,
    depth INTEGER NOT NULL,
    discovered_from TEXT,

    status TEXT NOT NULL DEFAULT 'PENDING',
    claimed_by TEXT,
    claimed_at TIMESTAMPTZ,
    attempts INTEGER NOT NULL DEFAULT 0,

    http_status INTEGER,
    error_message TEXT,
    completed_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- The dedupe key. Discovery re-inserts the same URL from every page that links to it;
-- ON CONFLICT DO NOTHING makes that free.
CREATE UNIQUE INDEX ux_crawl_queue_run_url ON crawl_queue_item (run_id, url);

-- Serves the claim statement's WHERE + ORDER BY. Breadth-first: shallower pages first, so a
-- run that hits its page budget has covered the pages nearest the entry points.
CREATE INDEX ix_crawl_queue_claim ON crawl_queue_item (run_id, status, depth, id);

-- Serves visitedUrls() and the live progress counts.
CREATE INDEX ix_crawl_queue_run_status ON crawl_queue_item (run_id, status);