-- Findings are the product (spec 6.2). Fingerprint is the identity; the two status columns are
-- the orthogonal axes of spec 6.3 — collapsing them is how acknowledging a finding erases the
-- fact that it is still broken.
CREATE TABLE finding (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT NOT NULL REFERENCES site (id) ON DELETE CASCADE,
    fingerprint TEXT NOT NULL,
    check_type TEXT NOT NULL,
    subject_key TEXT NOT NULL,
    location_key TEXT NOT NULL,          -- '*' when site-wide (spec 6.2's two-tier resolution)
    severity TEXT NOT NULL,
    message_key TEXT NOT NULL,
    message_args JSONB NOT NULL DEFAULT '[]'::jsonb,
    evidence JSONB,
    observed_status TEXT NOT NULL DEFAULT 'ACTIVE'
        CHECK (observed_status IN ('ACTIVE','RESOLVED')),
    triage_status TEXT NOT NULL DEFAULT 'UNTRIAGED'
        CHECK (triage_status IN ('UNTRIAGED','ACKNOWLEDGED','MUTED','WONT_FIX')),
    triage_reason TEXT,
    triaged_at TIMESTAMPTZ,
    -- Run ids are history, not live references: findings are kept indefinitely (spec 6.5) and
    -- must survive any later pruning of run rows, so these three carry no foreign key.
    first_seen_run BIGINT NOT NULL,
    last_seen_run BIGINT NOT NULL,
    resolved_at_run BIGINT,              -- kept after a regression: it is what makes one visible
    occurrence_count INTEGER NOT NULL DEFAULT 0,
    page_count INTEGER NOT NULL DEFAULT 0,   -- pages in the most recent run: "on 312 pages"
    first_seen_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX ux_finding_fingerprint ON finding (fingerprint);
CREATE INDEX ix_finding_site_open ON finding (site_id, observed_status, triage_status);
CREATE INDEX ix_finding_last_seen ON finding (last_seen_run);
CREATE INDEX ix_finding_resolved_at ON finding (resolved_at_run);

-- Occurrences keep every exact page, so promotion to '*' never loses detail (spec 6.2).
CREATE TABLE finding_occurrence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    finding_id BIGINT NOT NULL REFERENCES finding (id) ON DELETE CASCADE,
    run_id BIGINT NOT NULL,
    page_url TEXT,                       -- NULL for a site-scoped finding: there is no one page
    severity TEXT NOT NULL,
    message_key TEXT NOT NULL,
    message_args JSONB NOT NULL DEFAULT '[]'::jsonb,
    evidence JSONB,
    observed_at TIMESTAMPTZ NOT NULL
);

-- One row per finding per page per run. NULLS NOT DISTINCT so the site-scoped case dedupes too,
-- and so re-materialising a reclaimed run (spec 14) is an update rather than a duplicate.
CREATE UNIQUE INDEX ux_finding_occurrence ON finding_occurrence (finding_id, run_id, page_url)
    NULLS NOT DISTINCT;
CREATE INDEX ix_finding_occurrence_run ON finding_occurrence (run_id);

ALTER TABLE run ADD COLUMN findings_new INTEGER NOT NULL DEFAULT 0;
ALTER TABLE run ADD COLUMN findings_resolved INTEGER NOT NULL DEFAULT 0;
