package dev.hendrikhoemberg.webtesthelper.model;

import java.util.List;
import java.util.Locale;

/**
 * Heuristic classifier to determine whether an HTML element id was authored by a human
 * rather than generated by a web framework (§10.2).
 */
public final class AuthoredId {

    private static final int MAX_LENGTH = 64;
    private static final int MIN_HEX_LENGTH = 8;

    private static final List<String> GENERATOR_PREFIXES = List.of(
            "ember",
            "react-",
            "ng-",
            "mui-",
            "radix-",
            "headlessui-",
            "svelte-"
    );

    private AuthoredId() {
    }

    /**
     * Determines whether the given id looks authored rather than framework-generated (§10.2).
     *
     * @param id the HTML element id candidate
     * @return true if the id looks authored, false if it should be rejected
     */
    public static boolean looksAuthored(String id) {
        if (id == null || id.isBlank() || id.length() > MAX_LENGTH) {
            return false;
        }

        int length = id.length();
        int digitCount = 0;
        boolean allHex = true;

        for (int i = 0; i < length; i++) {
            char c = id.charAt(i);
            if (!isValidChar(c)) {
                return false;
            }
            if (c >= '0' && c <= '9') {
                digitCount++;
            } else if (!((c >= 'a' && c <= 'f') || (c >= 'A' && c <= 'F'))) {
                allHex = false;
            }
        }

        // Long hex match (^[0-9a-f]{8,}$ case-insensitive)
        if (length >= MIN_HEX_LENGTH && allHex) {
            return false;
        }

        // Digits are more than half the characters
        if (digitCount * 2 > length) {
            return false;
        }

        // Known framework generator prefixes (case-insensitive)
        String lower = id.toLowerCase(Locale.ROOT);
        for (String prefix : GENERATOR_PREFIXES) {
            if (lower.startsWith(prefix)) {
                return false;
            }
        }

        return true;
    }

    private static boolean isValidChar(char c) {
        return (c >= 'a' && c <= 'z')
                || (c >= 'A' && c <= 'Z')
                || (c >= '0' && c <= '9')
                || c == '_'
                || c == '-';
    }
}
